apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nextjs-deployment
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nextjs
  template:
    metadata:
      labels:
        app: frontend-nextjs
    spec:
      containers:
        - name: frontend-angular
          image: cristianbenavides/nextjs-fronted:latest
          ports:
            - containerPort: 3100  # Puerto donde Angular escucha

apiVersion: v1
kind: Service
metadata:
  name: frontend-nextjs-service
  namespace: devops-dev
spec:
  selector:
    app: frontend-nextjs
  ports:
    - protocol: TCP
      port: 80        # Puerto del servicio expuesto (público)
      targetPort: 3100  # Puerto donde Angular escucha dentro del contenedor
      nodePort: 30001   # Puerto accesible desde los nodos del clúster
  type: NodePort